name: action.yml
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dispatch and return Run ID
        uses: codex-/return-dispatch@v1.5.0
        id: return-dispatch
        with:
          token: ${{ secrets.ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected # or refs/heads/target_branch
          repo: aoeu-e2e
          owner: theartofeducation
          workflow: test.yml
          workflow_inputs: '{"cake":"delicious"}'
          workflow_timeout_seconds: 300 # Default: 300
      
      - name: Output fetched Run ID
        run: echo ${{ github.event.workflow_run.run_id }}

      - name: Evaluate that the Run ID output has been set
        run: |
          if [ "${{ steps.return_dispatch.outputs.run_id }}" == "" ]; then
            echo "Failed to return Run ID"
            exit 1
          fi
