name: gh-actions
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Dispatch and return Run ID
        uses: codex-/return-dispatch@v1.5.0
        id: return-dispatch
        with:
          token: ${{ secrets.ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected # or refs/heads/target_branch
          repo: aoeu-e2e
          owner: theartofeducation
          workflow: ci.yml
          workflow_inputs: '{"cake":"delicious"}'
          workflow_timeout_seconds: 100 # Default: 300

      - name: Evaluate that the Run ID output has been set
        run: |
          if [ "${{ steps.return_dispatch.outputs.run_id }}" == "" ]; then
            echo "Failed 2 return Run ID"
            exit 1
          fi
    
      - name: Output fetched Run ID
        run: echo ${{ steps.return_dispatch.outputs.run_id }}
          
      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.4.0
        with:
          token: ${{ github.token }}
          repo: aoeu-e2e
          owner: theartofeducation
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 300 # Optional
          poll_interval_ms: 5000 # Optional
