name: github-actions-test ci
on:
  push:
  pull-request:
    types: [converted_to_draft, ready_for_review]
jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      ##Found this fix here: https://github.com/actions/checkout/issues/14#issuecomment-523916396
      - name: Fix up git URLs
        run: echo -e '[url "git@github.com:"]\n  insteadOf = "https://github.com/"' >> ~/.gitconfig
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: theartofeducation/aoeu-e2e
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./.github/workflows/ci.yml
      - name: Run my action
        uses: ./.github/workflows/ci.yml
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

