name: github-actions-test ci
on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  test:
    name: Run GA Workflow from E2E
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -X POST https://api.github.com/repos/theartofeducation/aoeu-e2e/actions/workflows/16751183/dispatches \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -u ${{ secrets.ACCESS_TOKEN }} \
        --data '{"ref": "main"}'
