name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push: 
  workflow_dispatch:

jobs:
  test:
    name: Checkout the E2E Repository and Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Suppress Runner Error
        run: |
          git config --global init.defaultBranch main

      - name: Checkout Main Repo
        uses: actions/checkout@v2
        with:
          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected  

      - name: Check out E2E Repo and Run E2E Tests
        uses: actions/checkout@v2
        with:
          repository: theartofeducation/aoeu-e2e
          ref: main
          ssh-strict: false
          # The ACCESS.TOKEN needs to be added to this repository also
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
          path: .github/workflows/ci.yml
