name: github-actions-test ci
on:
  push:

jobs:
  test:
    name: Run GA Workflow from E2E
    runs-on: ubuntu-latest
    steps:
      - name: Check out E2E repository
        uses: actions/checkout@v3
        with:
          repository: theartofeducation/e2e
          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected
          username: jmosley5
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./.github/actions/e2e/ci.yml
        if: ${{ success() }}
            echo The tests passed!
      
  
    #runs-on: ubuntu-latest
    #steps:
    #- name: PING - Dispatch initiating repository event
      #if: github.event.action != 'pong'
      #run: |
        #curl \
         #-X POST \
         #-H "Accept: application/vnd.github.everest-preview+json" \
         #https://api.github.com/repos/theartofeducation/aoeu-e2e/dispatches \
         #-u ${{ secrets.ACCESS_TOKEN }} \
         #-d '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
    #- name: ACK - Acknowledge pong from remote repository
      #if: github.event.action == 'pong'
      #run: |
        #echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
        #curl -X POST https://api.github.com/repos/theartofeducation/aoeu-e2e/dispatches \
        #-H 'Accept: application/vnd.github.everest-preview+json' \
        #-u ${{ secrets.ACCESS_TOKEN }} \
        #-d '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'  
