name: github-actions-test ci
on:
  push:
  workflow_dispatch:
jobs:
  checkout-repository:
    name: Run GA Workflow from E2E
    runs-on: ubuntu-latest
    env:
      E2E_TESTS_BASE_URL: ${{ secrets.E2E_TESTS_BASE_URL }}
    steps:
      - name: Check out E2E repository
        uses: actions/checkout@v3
        ## fix found here: https://github.com/rectorphp/rector/commit/2243a814457690f61b38cfbb63421f7812a3b43c
        if: github.event.push.head.repo.full_name == github.repository
        with:
          repository: theartofeducation/aoeu-e2e
          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected
          token: ${{ secrets.ACCESS_TOKEN }}
          path: .github/workflows/ci.yml
