name: github-actions-test ci
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Run GA Workflow from E2E
    runs-on: ubuntu-latest
    steps:
    - name: Wait for tests to succeed
      uses: aurelien-baudet/workflow-dispatch@v2
      with:
        workflow: aoeu-e2e ci
        token: ${{ secrets.PERSONAL_TOKEN }}
        wait-for-completion: true
        outputs: workflow-conclusion
    - run: |
        curl \
         -X POST \
         -H "Accept: application/vnd.github.everest-preview+json" \
         https://api.github.com/repos/theartofeducation/aoeu-e2e/actions/workflows/ci.yml/dispatches \
         -u ${{ secrets.ACCESS_TOKEN }} \
         -d '{"ref":"chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected"}'
    ##- uses: actions/github-script@v6
      ##with:
        ##script: |
          ##await github.rest.actions.createWorkflowDispatch({
            ##owner: 'theartofeducation',
            ##repo: 'aoeu-e2e',
            ##workflow_id: 'ci.yml',
            ##ref: 'chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected'
          ##})
      ##env:
        ##ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
