name: github-actions-test ci
on:
  push:
  workflow_dispatch:
jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      ##Found this fix here: https://github.com/actions/checkout/issues/14#issuecomment-523916396
      - name: Fix up git URLs
        run: echo -e '[url "git@github.com"]\n  insteadOf = "https://github.com/"' >> ~/.gitconfig
      - name: Check out repository
        uses: actions/checkout@v2.3.4
        with:
          repository: theartofeducation/aoeu-e2e
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./.github/actions/aoeu-e2e
      - name: Run my action
        uses: ./.github/actions/aoeu-e2e/ci.yml
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

