name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push:
jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      - name: Suppress Runner Error
        run: |
          git config --global init.defaultBranch main 

      - name: run e2e tests
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | gh auth login --with-token
          gh workflow run ci.yml --ref main --repo theartofeducation/aoeu-e2e
          gh workflow view ci.yml --repo theartofeducation/aoeu-e2e
          gh api "/repos/theartofeducation/aoeu-e2e/actions/runs?status=in_progress" -q '. | select(.total_count == 1) | .workflow_runs[0].id'


     