name: github-actions-test ci
on:
  push:
  workflow_dispatch:
    inputs:
      github-token: ${{ secrets.GH_PAT }}
jobs:
  test:
    name: Run GA Workflow from E2E
    runs-on: ubuntu-latest
    steps:
    ##- run: |
        ##curl \
         ##-X POST \
         ##-H "Accept: application/vnd.github.everest-preview+json" \
         ##https://api.github.com/repos/theartofeducation/aoeu-e2e/actions/workflows/ci.yml/dispatches \
         ##-u ${{ secrets.ACCESS_TOKEN }} \
         ##-d '{"ref":"chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected"}'
    ##- uses: actions/github-script@v6
      ##with:
        ##script: |
          ##await github.rest.actions.createWorkflowDispatch({
            ##owner: 'theartofeducation',
            ##repo: 'aoeu-e2e',
            ##workflow_id: 'ci.yml',
            ##ref: 'chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected'
          ##})
    - uses: octokit/request-action@v2.x
      id: create_check_run
      with:
        route: POST /repos/theartofeducation/aoeu-e2e/actions/workflows/ci.yml/dispatches
        owner: octokit
        repo: aoeu-e2e
        name: "Test check run"
        head_sha: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
