name: github-actions-test ci
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Run GA Workflow from E2E
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -X POST \
        -H "Accept: application/vnd.github.everest-preview+json" \
        https://api.github.com/repos/theartofeducation/aoeu-e2e/actions/workflows/16751183/dispatches \
        -u ${{ secrets.ACCESS_TOKEN }} \
        --data --raw-field event_type=mytrigger
