name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push:
jobs:
  run-tests-from-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Suppress Runner Error
        run: |
          git config --global init.defaultBranch main

      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1.5.0
        id: return-dispatch
        with:
          token: ${{ secrets.ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected # or refs/heads/target_branch
          repo: aoeu-e2e
          owner: theartofeducation
          workflow: ci.yml
          workflow_timeout_seconds: 100 # Default: 300

      - name: Await Remote Run
        uses: Codex-/await-remote-run@v1.4.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repo: github-actions-test
          owner: theartofeducation
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 300 # Optional
          poll_interval_ms: 5000 # Optional


     