name: github-actions-test ci
on:
  push:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
jobs:
  test:
    name: Run GA Workflow from E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
  call-workflow-passing-data:
    uses: theartofeducation/aoeu-e2e/.github/workflows/ci.yml@chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected
    with:
      username: DollyParton
    secrets:
      envPAT: ${{ secrets.ACCESS_TOKEN }}
  
    #runs-on: ubuntu-latest
    #steps:
    #- name: PING - Dispatch initiating repository event
      #if: github.event.action != 'pong'
      #run: |
        #curl \
         #-X POST \
         #-H "Accept: application/vnd.github.everest-preview+json" \
         #https://api.github.com/repos/theartofeducation/aoeu-e2e/dispatches \
         #-u ${{ secrets.ACCESS_TOKEN }} \
         #-d '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
    #- name: ACK - Acknowledge pong from remote repository
      #if: github.event.action == 'pong'
      #run: |
        #echo "PONG received from '${{ github.event.client_payload.repository }}'" && \
        #curl -X POST https://api.github.com/repos/theartofeducation/aoeu-e2e/dispatches \
        #-H 'Accept: application/vnd.github.everest-preview+json' \
        #-u ${{ secrets.ACCESS_TOKEN }} \
        #-d '{"event_type": "ack", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'  
