name: github-actions-test ci
on:
  push:
  workflow_dispatch:
jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
      ##Found this fix here: https://github.com/actions/checkout/issues/14#issuecomment-523916396
      - name: Fix up git URLs
        run: echo -e '[url "git@github.com:"]\n  insteadOf = "https://github.com/"' >> ~/.gitconfig
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: theartofeducation/aoeu-e2e
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./.github/workflows/ci.yml
      - name: Run my action
        uses: ./.github/workflows/ci.yml
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

