name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push: 
  workflow_dispatch:

jobs:
  test:
    name: Checkout the E2E Repository and Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Suppress Runner Error
        run: |
          git config --global init.defaultBranch main

      - name: Checkout Main Repo
        uses: actions/checkout@v2
        with:
          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected 

    ##Found this fix here: https://github.com/actions/checkout/issues/14#issuecomment-523916396
      ##- name: Fix up git URLs
        ##run: echo -e '[url "git@github.com:"]\n  insteadOf = "https://github.com/"' >> ~/.gitconfig    

      - name: Check out E2E Repo
        uses: actions/checkout@v2
        with:
          repository: theartofeducation/aoeu-e2e
          ref: main
          ssh-strict: false
          # GitHub's personal access token with access to `my-organization/awesome-action`
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
          path: .github/actions/ci.yml

      ##- name: Check out E2E Repo
        ##run: |
          ##run: git clone --single-branch --no-tags --depth 1 -b master https://@github.com/theartofeducation/aoeu.e2e ./.github/actions/ci.yml
   
      - name: Run my workflow action
        uses: ./.github/actions/aoeu-e2e-ci
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

