name: github-actions-test ci
on:
  push:
  workflow_dispatch:
jobs:
  checkout-repository:
    name: Run GA Workflow from E2E
    uses: theartofeducation/aoeu-e2e/.github/workflows/ci.yml@main
    runs-on: ubuntu-latest
