name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push: 
  workflow_dispatch:

jobs:
  test:
    name: Checkout the E2E Repository and Run tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected

      - name: Clone the E2E Repo
        run: git clone --single-branch --no-tags --depth 1 -b master https://github.com/theartofeducation/aoeu-e2e ./.github/actions/ci.yml
   
      - name: Run my action
        uses: actions/checkout@v2
        with:
          repository: theartofeducation/aoeu-e2e
          token: ${{ secrets.ACCESS_TOKEN }}
          ssh-key: ${{ secrets.PERSONAL_TOKEN }}
          path: actions/workflows/ci.yml

