name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push: 
  workflow_dispatch:
jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      ##Found this fix here: https://github.com/actions/checkout/issues/14#issuecomment-523916396
      - name: Fix up git URLs
        run: echo -e '[url "git@github.com:"]\n  insteadOf = "https://github.com/"' >> ~/.gitconfig 

      - uses: shaunco/ssh-agent@git-repo-mapping
        with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        repo-mappings: github.com/theartofeducation/aoeu-e2e 

      - name: Check out repository
        uses: actions/checkout@v2.3.4
        with:
          repository: theartofeducation/aoeu-e2e
          ref: main
          path: ./.github/workflows/ci.yml
          token: ${{ secrets.ACCESS_TOKEN }}
   
      - name: Run my action
        uses: ./.github/workflows/ci.yml
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

