name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push:
  workflow_run:
    workflows: ["aoeu-e2e"]
    types: [completed]
jobs:
  run-tests-from-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Suppress Runner Error
        run: |
          git config --global init.defaultBranch main

      - name: Dispatch an action and get the run ID
        uses: codex-/return-dispatch@v1
        id: return-dispatch
        with:
          token: ${{ secrets.ACCESS_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected # or refs/heads/target_branch
          repo: aoeu-e2e
          owner: theartofeducation
          workflow: ci.yml
          workflow_timeout_seconds: 120 # Default: 300

      - name: Use the output run ID
        run: echo ${{steps.return-dispatch.outputs.run_id}}

      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repo: github-actions-test
          owner: theartofeducation
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 300 # Optional
          poll_interval_ms: 5000 # Optional

      ##- name: run e2e tests
        ##run: |
          ##echo ${{ secrets.ACCESS_TOKEN }} | gh auth login --with-token
          ##gh workflow run ci.yml --ref chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected --repo theartofeducation/aoeu-e2e


    


     