name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push:
  workflow_run:
    workflows: ["aoeu-e2e"]
    types: [completed]
jobs:

  run-tests-from-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Suppress Runner Error
        run: |
          git config --global init.defaultBranch main

      - name: run e2e tests
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} | gh auth login --with-token
          gh workflow run ci.yml --ref chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected --repo theartofeducation/aoeu-e2e
          gh run view --log --job 6906125036 --repo theartofeducation/aoeu-e2e

  retrieve-test-run:
    steps: 
      hello-test:
        uses: theartofeducation/aoeu-e2e/.github/workflows/ci.yml@chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected
        with: 
          token: ${{ secrets.ACCESS_TOKEN}}
  job2:
    runs-on: ubuntu-latest
    needs: hello-test
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}


     