name: github-actions-test ci
on:
  push:
  workflow_dispatch:
jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          repository: theartofeducation/aoeu-e2e
          ref: main
          path: ./.github/actions/aoeu-e2e
      - name: Run my action
        uses: ./.github/actions/aoeu-e2e/ci.yml

