name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push: 
  workflow_run:
    workflows: [aeou-e2e ci]
    types:
      - completed

jobs:
  test:
    name: Checkout the E2E Repository and Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Suppress Runner Error
        run: |
          git config --global init.defaultBranch main  

      - name: Check out E2E Repo and Run E2E Tests
        uses: actions/checkout@v2
        with:
          repository: git@github.com:theartofeducation/aoeu-e2e.git
          ref: main
          path: .github/workflows/ci.yml
          ssh-strict: false
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false
