name: github-actions-test ci
on:
  push:
  repository_dispatch:
jobs:
  test:
    name: Run GA Workflow from E2E
    runs-on: ubuntu-latest
    steps:
    - name: PING - Dispatch initiating repository event
      if: github.event.action != 'pong'
      run: |
        curl \
         -X POST \
         -H "Accept: application/vnd.github.everest-preview+json" \
         https://api.github.com/repos/theartofeducation/aoeu-e2e/actions/workflows/ci.yml/dispatches \
         -u ${{ secrets.ACCESS_TOKEN }} \
         -d '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
