name: github-actions-test ci
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: Run GA Workflow from E2E
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl \
         -X POST \
         -H "Accept: application/vnd.github.everest-preview+json" \
         https://api.github.com/repos/theartofeducation/aoeu-e2e/actions/workflows/ci.yml/dispatches \
         -u ${{ secrets.ACCESS_TOKEN }} \
         -d '{"ref":"main","inputs":{"name":"Mona the Octocat"}}'
