name: github-actions-test ci
on:
  pull_request:
    types: [ready_for_review]
  push:
jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      - name: Suppress Runner Error
        run: |
          git config --global init.defaultBranch main 
      # https://github.com/marketplace/actions/github-status-action
      - name: set pending status
        uses: Sibz/github-status-action@v1
        with:
          repository: theartofeducation/aoeu-e2e
          owner: "Judy Mosley <judymosley@theartofeducation.edu>"
          authToken: ${{ secrets.ACCESS_TOKEN }}
          context: 'E2E tests'
          description: 'Tests pending deploy'
          # success, error, failure, or pending
          state: 'pending'
          sha: ${{github.event.pull_request.head.sha}} 

      ##- name: Check out E2E Repo and Run E2E Tests
        ##uses: actions/checkout@v2
        ##with:
          ##repository: theartofeducation/aoeu-e2e
          ##ref: chore/sc-7778/if-a-test-fails-in-the-e2e-repo-it-gets-reflected
          ##path: .github/workflows/ci.yml
          ##ssh-strict: false
          ##token: ${{ secrets.ACCESS_TOKEN }}
          ##persist-credentials: false

     